site_name: Paul Leone â€“ Projects & Portfolio

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - toc.follow        # Add this
    - toc.integrate     # Optional: integrates TOC into left nav 
  icon:
    logo: material/shield-account

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Projects:
      - Business Intelligence & Data Analytics: projects/business-intelligence.md
      - Threat Intelligence Brief & SOC Improvement Plan: projects/threat-intel.md
      - Security Homelab:
          - Overview: projects/homelab/index.md
          - Executive Summary: projects/homelab/01-exec-summary.md
          - Platform and Virtualization: projects/homelab/02-platform.md
          - Network Security: projects/homelab/03-network.md
          - Identity Access and Secrets: projects/homelab/04-iam-secrets.md
          - Observability and SIEM: projects/homelab/05-auto-iac.md
          - Detection and Response: projects/homelab/06-apps-service.md
          - Automation and SOAR: projects/homelab/07-vis-response-pt1.md
          - Hardware and Deployment: projects/homelab/08-vis-response-pt2.md
          - GRC Frameworks:
              - GRC Overview: projects/homelab/grc/grc-index.md
              - GRC Summary: projects/homelab/grc/01-summary.md
              - NIST CSF: projects/homelab/grc/grc-nist-csf.md
              - NIST SP 800-53: projects/homelab/grc/grc-nist-800.md
              - CIS Controls: projects/homelab/grc/grc-cis-controls.md
              - ISO 27001: projects/homelab/grc/grc-iso27001.md
              - Mitre Att&ck: projects/homelab/grc/grc-mitre.md
              - OWASP 2025: projects/homelab/grc/owasp.md
              - CISA & NIST Zero Trust: projects/homelab/grc/zero-trust.md
